# Generated by Django 4.1.2 on 2022-10-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logreg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itm',
            name='id',
        ),
        migrations.AlterField(
            model_name='itm',
            name='Item_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
