# Generated by Django 4.1.2 on 2022-10-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logreg', '0002_remove_itm_id_alter_itm_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='Product_Name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
