# Generated by Django 4.1.2 on 2022-10-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logreg', '0003_alter_pro_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=30)),
                ('Item_name', models.CharField(max_length=30)),
                ('Stock', models.IntegerField()),
            ],
        ),
    ]
